name: Generate Premium PDF (on demand & on project change)

on:
  workflow_dispatch:
    inputs:
      project:
        description: 'Project folder (e.g., projects/Bezpieczny_Pieszy)'
        required: false
        default: 'projects/Bezpieczny_Pieszy'
  push:
    paths:
      - 'projects/**'
      - 'assets/logos/**'
      - 'assets/fonts/**'
      - 'tools/generate_premium_pdf.py'
      - 'pdf/config.json'

permissions:
  contents: write

jobs:
  render_pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install reportlab
      - name: Generate PDF
        env:
          TZ: Europe/Warsaw
        run: |
          python tools/generate_premium_pdf.py "${{ github.event.inputs.project }}"
      - name: Commit PDF
        run: |
          git config --global user.name "PPB Bot"
          git config --global user.email "github93@wp.pl"
          git add pdf/*.pdf
          git commit -m "Premium PDF auto-render [skip ci]" || echo "No changes"
          git pull --rebase --autostash
          git push
