name: Weekly Email Summary (Sunday 20:05 Warsaw)

on:
  schedule:
    - cron: "5 18 * * 0"   # Sundays 18:05 UTC ~ 20:05 Warsaw
  workflow_dispatch:

permissions:
  contents: read

jobs:
  weekly_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Build weekly summary and send email
        env:
          TZ: Europe/Warsaw
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          MAIL_TO:   ${{ secrets.MAIL_TO }}
          MAIL_FROM: ${{ secrets.MAIL_FROM }}
        run: |
          python tools/generate_weekly_summary.py
          python tools/email_send.py
