name: Daily Report (20:00 Warsaw)

on:
  schedule:
    - cron: "0 18 * * *"   # 20:00 Europe/Warsaw (UTC cron)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  daily_report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Generate daily combined report
        env:
          TZ: Europe/Warsaw
        run: |
          python tools/generate_report.py

      - name: Commit daily report
        run: |
          git config --global user.name "PPB Bot"
          git config --global user.email "github93@wp.pl"
          git add reports/daily
          git commit -m "Daily combined report [skip ci]" || echo "No changes"
          git pull --rebase --autostash
          git push
