name: Auto Report (PPB)

on:
  schedule:
    - cron: "0 * * * *"   # co godzinę
  workflow_dispatch:       # ręczne uruchomienie

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate report
        run: |
          python tools/generate_report.py

      - name: Send report via email
        run: |
          python tools/email_sender.py

      - name: Commit report
        run: |
          git config --global user.name "PPB Bot"
          git config --global user.email "github93@wp.pl"
          git add reports/latest_report.md
          git commit -m "Update hourly report" || echo "No changes"
          git push
