- name: Send report via email
  env:
    SMTP_HOST: ${{ secrets.SMTP_HOST }}
    SMTP_PORT: ${{ secrets.SMTP_PORT }}
    SMTP_USER: ${{ secrets.SMTP_USER }}
    SMTP_PASS: ${{ secrets.SMTP_PASS }}
    MAIL_FROM: ${{ secrets.MAIL_FROM }}
    MAIL_TO:   ${{ secrets.MAIL_TO }}
    TZ:        ${{ secrets.TZ }}
  run: |
    python tools/email_sender.py
