name: Daily Email Report

on:
  schedule:
    - cron: "0 18 * * *"   # 18:00 UTC = 20:00 czasu polskiego
  workflow_dispatch:       # możliwość ręcznego uruchomienia

permissions:
  contents: write

jobs:
  daily_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate daily report
        run: |
          python tools/generate_report.py

      - name: Send report via email (with attachments)
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          MAIL_FROM: ${{ secrets.MAIL_FROM }}
          MAIL_TO:   ${{ secrets.MAIL_TO }}
        run: |
          python tools/email_sender.py

      - name: Commit & push daily confirmation
        run: |
          git config --global user.name "PPB Bot"
          git config --global user.email "github93@wp.pl"
          git add reports/
          git commit -m "Daily report - $(date '+%Y-%m-%d %H:%M')" || echo "No changes"
          git push
