
name: Daily Email (20:00 Warsaw)
on:
  schedule:
    - cron: "0 18 * * *"   # 20:00 Warsaw ~= 18:00 UTC
  workflow_dispatch:
permissions:
  contents: write
jobs:
  daily_email:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Warsaw
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
      - name: Generate daily report
        run: |
          python tools/generate_report.py --mode daily
      - name: Send report via email
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          MAIL_FROM: ${{ secrets.MAIL_FROM }}
          MAIL_TO:   ${{ secrets.MAIL_TO }}
        run: |
          python tools/email_sender.py
      - name: Commit & push daily confirmation
        run: |
          git config --global user.name "PPB Bot"
          git config --global user.email "github93@wp.pl"
          git add -A
          git stash || true
          git fetch origin
          git checkout main
          git pull origin main --rebase || true
          git stash pop || true
          git add -A
          git commit -m "Daily report email sent [skip ci]" || echo "Nothing to commit"
          git push
