name: Daily Email (20:00 Warsaw)

on:
  schedule:
    - cron: "0 18 * * *"   # 20:00 Warsaw
  workflow_dispatch:

permissions:
  contents: write

env:
  TZ: Europe/Warsaw
  MAIN_BRANCH: main

jobs:
  daily:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate daily report
        run: |
          python tools/generate_report.py --mode daily

      - name: Send email
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          MAIL_FROM: ${{ secrets.MAIL_FROM }}
          MAIL_TO:   ${{ secrets.MAIL_TO }}
          MODE: daily
        run: |
          python tools/email_sender.py

      - name: Commit & push (GH_TOKEN)
        run: |
          git config --global user.name  "PPB Bot"
          git config --global user.email "github-bot@example.com"
          git pull --rebase origin ${{ env.MAIN_BRANCH }} || true
          git add reports/daily/ .
          git commit -m "daily: store sent [skip ci]" || echo "No changes"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} ${{ env.MAIN_BRANCH }}
