name: Hourly Reports

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write

env:
  TZ: Europe/Warsaw
  MAIN_BRANCH: main

jobs:
  hourly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate hourly report
        run: |
          python tools/generate_report.py --mode hourly

      - name: Commit & push (GH_TOKEN)
        run: |
          git config --global user.name  "PPB Bot"
          git config --global user.email "github-bot@example.com"
          git pull --rebase origin ${{ env.MAIN_BRANCH }} || true
          git add reports/hourly/ .
          git commit -m "hourly: update [skip ci]" || echo "No changes"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} ${{ env.MAIN_BRANCH }}
