
name: PPB Reports
on:
  schedule:
    - cron: "0 * * * *"   # co godzinę (UTC)
  workflow_dispatch:
permissions:
  contents: write
jobs:
  hourly_report:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Warsaw
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
      - name: Generate hourly report
        run: |
          python tools/generate_report.py --mode hourly
      - name: Commit & push hourly report
        run: |
          git config --global user.name "PPB Bot"
          git config --global user.email "github93@wp.pl"
          git add -A
          git stash || true
          git fetch origin
          git checkout main
          git pull origin main --rebase || true
          git stash pop || true
          git add -A
          git commit -m "Hourly report [skip ci]" || echo "Nothing to commit"
          git push
