name: PAT Smoke Test
on: { workflow_dispatch: {} }
permissions: { contents: write }
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Write a test file
        run: |
          mkdir -p reports
          echo "Smoke test $(date -u)" > reports/_pat_check.txt
      - name: Commit & push (PAT)
        env:
          MACHINE_PAT: ${{ secrets.MACHINE_PAT }}
          GIT_AUTHOR_NAME: "PPB Bot"
          GIT_AUTHOR_EMAIL: "github93@wp.pl"
          GIT_COMMITTER_NAME: "PPB Bot"
          GIT_COMMITTER_EMAIL: "github93@wp.pl"
        run: |
          bash tools/commit_with_pat.sh "chore: PAT smoke test" "reports/_pat_check.txt"
