name: PPB Reports (daily 20:00 CET)

on:
  schedule:
    # 18:00 UTC = 20:00 Europe/Warsaw (czas letni/zimowy ogarnia UTC)
    - cron: "0 18 * * *"
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  daily_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate daily report
        run: |
          python tools/generate_report.py

      - name: Send report via email
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          MAIL_FROM: ${{ secrets.MAIL_FROM }}   # np. TwojLogin@gmail.com
          MAIL_TO:   ${{ secrets.MAIL_TO }}     # np. TwojLogin@gmail.com
        run: |
          python tools/email_sender.py

      - name: Upload report as artifact (podgląd w Actions)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: daily-report
          path: |
            reports/latest_report.md
            reports/*.zip
