name: Weekly Email Summary (Sunday 20:00 Warsaw)

on:
  schedule:
    - cron: "0 18 * * 0"   # 20:00 Warsaw on Sunday
  workflow_dispatch:

permissions:
  contents: write

env:
  TZ: Europe/Warsaw
  MAIN_BRANCH: main

jobs:
  weekly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate weekly report
        run: |
          python tools/generate_report.py --mode weekly

      - name: Send email
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          MAIL_FROM: ${{ secrets.MAIL_FROM }}
          MAIL_TO:   ${{ secrets.MAIL_TO }}
          MODE: weekly
        run: |
          python tools/email_sender.py

      - name: Commit & push (GH_TOKEN)
        run: |
          git config --global user.name  "PPB Bot"
          git config --global user.email "github-bot@example.com"
          git pull --rebase origin ${{ env.MAIN_BRANCH }} || true
          git add reports/weekly/ .
          git commit -m "weekly: store sent [skip ci]" || echo "No changes"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} ${{ env.MAIN_BRANCH }}
